# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffd4e3f2a17a35d2529d22cdd94284b0e04e5e7da50ab8f16200bd38b67e41e8838eaa49333c5e7d59196ae56baf2d86115b73e2935585fd5f6ac18292701559

test:
  secret_key_base: 7fd772c1935e5c4a3aee5f2693da26cecd2823826eaf1ec6437c4e795ab0141533cb818b311876a9513327b154a146076495a82ce3c1f63e8e3af3d7fe9e4e4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
